springdoc:
  api-docs:
    enabled: true
    ## Swagger ??? ??????.

  swagger-ui:
    path: /swagger-ui
    ## Swagger UI? ??? ??? ??. ???? '/swagger-ui.html'.

    disable-swagger-default-url: true
    ## Swagger?? ?? ???? ?? API ?? ????.

    display-request-duration: true
    ## 'Try it out' ?? ? ?? ?? ??? ??.

    tags-sorter: alpha
    ## ??? ??? ??? ??.

    operations-sorter: alpha
    ## API ???? ??? ??? ??.

    doc-expansion: none
    ## ?? ?? ? ????? API? ?? ??? ??.

    syntax-highlight:
      theme: nord
      ## Swagger UI? ?? ?? ??? 'nord'? ??.

    urls-primary-name: HR AUTOASSIGN API
    ## Swagger UI ?? ? ???? API ??.

    persist-authorization: true
    ## ?? ?? ??? ?? ?? ??? ??.

    query-config-enabled: true
    ## Swagger UI?? ??? ?? ????? ?? ????? ??.

  pre-loading-enabled: true
  ## ???? ?? ? OpenAPI ??? ?? ??.

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    ## Docker ???? ? MySQL? ???? ?? URL. ?? ??? ??.
    username: ${DB_USER}
    ## MySQL ????.
    password: ${DB_PASSWORD}
    ## MySQL ????.

  jpa:
    hibernate:
      ddl-auto: update
      ## Hibernate? ?????? ???? ???? ??????? ??. ?? ?? ??.

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ## MySQL 8.x ??? ?? Hibernate ??? ??.
  server:
    port: 8080
    ## ?? ??? 8080?? ??